version: '3'

services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data_prod:/data/db
      
    backend:
        build:
            context: ../backend/
            dockerfile: ./dockerfiles/prod.Dockerfile
        ports:
            - "8080:8080"
        environment:
            - MONGO_URI=mongodb://mongodb:27017/phonebook
        depends_on: 
            - mongodb

    frontend:
        build:
            context: ../frontend/
            dockerfile: ./dockerfiles/prod.Dockerfile
        ports:
            - "81:80"
        tty: true # Quick hack: https://github.com/facebook/create-react-app/issues/8688
